version: '3'
services:

  php-fpm10:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args: [ "GID=${gid}", "UID=${uid}" ]
    user: ${uid}:${gid}
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php-fpm
      SERVICE_TAGS: dev
      UID: ${uid}
      GID: ${gid}
    working_dir: /var/www/app
    volumes:
      - ./src:/var/www/app
      - /tmp:/tmp
      - ./log/php:/usr/local/var/log/
      - ./log/laravel:/var/www/app/storage/logs
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: nginx
      SERVICE_TAGS: dev
      UID: ${uid}
      GID: ${gid}
    ports:
      - "192.168.0.113:9785:80"
    volumes:
      - ./src:/var/www/app
      - ./docker/nginx/etc:/etc/nginx
      - ./log/nginx:/var/log/nginx
    networks:
      - app-network

  mysql:
    image: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - "127.0.0.1:3371:3306"
    environment:
      MYSQL_DATABASE: activity
      MYSQL_USER: activity
      MYSQL_PASSWORD: z27nF4MGHwEo
      MYSQL_ROOT_PASSWORD: doIe8x0OscQz
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - ./data/mysql:/var/lib/mysql/
      - ./docker/mysql:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    networks:
      - app-network

  redis:
    image: redis:6.2.6
    environment:
      SERVICE_NAME: redis
      SERVICE_TAGS: dev
      UID: ${uid}
      GID: ${gid}
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./data/redis:/data
      - ./log/redis:/var/log/redis
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local
